language: python
sudo: false

python:
  - 2.7

install:
  - wget https://bootstrap.pypa.io/bootstrap-buildout.py
  - python bootstrap-buildout.py
  - travis_retry bin/buildout

script: bin/py setup.py test -q

